#' chartScatter
#' Creates a scatter plot that can either be displayed for saved to disk.
#' A legend can be shown
#'
#' @param aX: X values
#' @param aY: Y values
#' @param aColor: Color for the X,Y points
#' @param aSavePlot: True if a chart file is desired
#' @param aYRange: Range of the Y axis
#' @param aXRange: Range of the X axis
#' @param aXLabel: X axis label
#' @param aYLabel: Y axis label
#' @param aTitle: Title of the chart
#' @param aShowFittedLine: True if to show a fitted line for the X,Y points
#' @param aShowSubset: True if to show a additional points on the chart
#' @param aSubsetX: X values for the additional points to display in a highlighted fashion
#' @param aSubsetY: Y values for the additional points to display in a highlighted fashion
#' @param aShowLegend: True to show legend
#' @param aLegend: Legend entries
#' @param aSavePlotFilename: Filename of the chart if the saved option is selected
#' @param aWidth: Width of the chart
#' @param aHeight: Height of the chart
#'
#' @return
#' @export
#'
#' @examples
#' chartScatter(
#'  aX = sba_dem$PercentFreeorReducedPricedMeals, aY = sba_dem$MathPercentMetStandardIncludingPrevPass,
#'  aTitle = "WA Public Schools",
#'  aXLabel = "% low income students \n \n Source: OSPI", aYLabel = "% of 8th Graders Who Met Standard in Math",
#'  aSubsetX = sba_dem_subset$PercentFreeorReducedPricedMeals,
#'  aSubsetY = sba_dem_subset$MathPercentMetStandardIncludingPrevPass, aShowSubset = T,
#'  aColor = "lightgray",
#'  aShowLegend = T, aLegend = sba_dem_subset$School, aShowFittedLine = T,
#' )

chartScatter <- function(aX, aY, aColor = 1, aSavePlot = F,
                         aYRange = c(0,100), aXRange = c(0,100), aXLabel = "", aYLabel =
                           "",
                         aTitle = "", aShowFittedLine = F,
                         aShowSubset = F, aSubsetX, aSubsetY,
                         aShowLegend = F, aLegend,
                         aSavePlotFilename = "ReportsAutoGenerated//Chart_Scatter.png",
                         aWidth = 1700, aHeight = 850) {
  yLabel = aYLabel
  
  if (aSavePlot) {
    png(
      file = aSavePlotFilename, width = aWidth, height = aHeight, pointsize =
        16
    )
    par(
      mar = c(12.1, 7.1, 4.1, 14.1), xpd = TRUE, mgp = c(4, 1, 0)
    ) #mgp adjusts the label positions
  } else {
    par(
      mar = c(12.1, 7.1, 4.1, 12.1), xpd = TRUE, mgp = c(4, 1, 0)
    ) #mgp adjusts the label positions
  }
  
  if (aShowFittedLine) {
    scatter.smooth(
      x = aX, y = aY,
      ylim = aYRange, xlim = aXRange,
      xlab = aXLabel,
      ylab = aYLabel, col = aColor, bg = aColor, pch = 19, cex = 1.5
    )
    
  } else {
    plot(
      x = aX, y = aY,
      ylim = aYRange, xlim = aXRange,
      xlab = aXLabel,
      ylab = aYLabel, col = aColor, bg = aColor, pch = 19, cex =
        1.5
    )
  }
  
  title(aTitle)
  #Plot subset points
  if (aShowSubset) {
    points(
      x = aSubsetX, y = aSubsetY, col = "black",
      bg = c(1:length(aSubsetX)), pch = 21, cex = 1.9
    )
  }
  #Show legend
  if (aShowLegend) {
    legend(
      "topright",inset = c(-0.20,0), legend =
        aLegend,
      col = c(1:length(aLegend)), pch = 19
    )
  }
  par(xpd = F)
  grid(NULL,NULL)
  if (aSavePlot) {
    dev.off()
  }
}
