source("chart_scatter.R")

#' genSBADataframe
#' Returns a dataframe with SBA data and demographics for each school for the selected grade.
#' Filter parameters include a min school enrollment, min number of test takers
#'
#' Input data files used:
#'   DataFilesRaw//1_2_Demographic Information by School 2015.csv
#'   DataFilesRaw//2_23_SBA Scores by School 2014-2015.csv
#'
#' @param aGrade: Grade to filter on
#' @param aMinEnrollment: Min enrollment for schools to filter schools on
#' @param aMinTestTakers: Min number of test takers to filter schools on
#'
#' @return sba_dem: A dataframe with merged SBA data and demographics
#' @export
#'
#' @examples
#' sba_dem <- genSBADataframe()
genSBADataframe <-
  function(aGrade = 8, aMinEnrollment = 200, aMinTestTakers = 10) {
    #Read demographics file
    demographics <-
      read.csv("DataFilesRaw//1_2_Demographic Information by School 2015.csv")
    #Reduce to pertinent columns
    demographics <-
      demographics[,c(
        "PercentFreeorReducedPricedMeals","District","School","BuildingNumber","TotalEnrollment"
      )]
    #Read sba file
    sba <-
      read.csv("DataFilesRaw//2_23_SBA Scores by School 2014-2015.csv")
    #Filter on grade specified
    sba_filtered <- sba[sba$GradeTested == aGrade,]
    #Reduce to pertinent columns
    sba_filtered <- sba_filtered[,c(
      "GradeTested",
      "MathPercentMetStandardIncludingPrevPass","MathPercentLevel4","MathTotalTested",
      "ELAPercentMetStandardIncludingPrevPass","ELAPercentLevel4","ELATotalTested",
      "BuildingNumber"
    )]
    
    #Merge files on building number
    sba_dem <-
      merge(sba_filtered, demographics, by = "BuildingNumber")
    
    #Filter on min size school and number of test takers
    sba_dem <- sba_dem[sba_dem$TotalEnrollment > aMinEnrollment,]
    sba_dem <- sba_dem[sba_dem$MathTotalTested > aMinTestTakers,]
    sba_dem <- sba_dem[sba_dem$ELATotalTested > aMinTestTakers,]
    #Remove rows with NA in school name
    sba_dem <- sba_dem[!is.na(sba_dem$School),]
    #Reduce to pertinent columns
    sba_dem <-
      sba_dem[,c(
        "BuildingNumber","PercentFreeorReducedPricedMeals","District","School",
        "MathPercentMetStandardIncludingPrevPass","MathPercentLevel4",
        "ELAPercentMetStandardIncludingPrevPass","ELAPercentLevel4",
        "TotalEnrollment"
      )]
    
    #Sort
    sba_dem <-
      sba_dem[order(sba_dem$PercentFreeorReducedPricedMeals),]
    sba_dem
  }

#' genSBAUseCases
#' Uses the genSBADataframe() function to generate a data frame to then create charts (using the chartScatter() method)
#' for each school district.
#'
#' @return
#' @export
#'
#' @examples
#' genSBAUseCases()
genSBAUseCases <- function() {
  sba_dem <-
    genSBADataframe(
      aGrade = 8, aMinEnrollment = 200, aMinTestTakers = 10
    )
  
  #Selected school districts
  sba_dem_districts <- sba_dem$District
  sba_dem_districts <-
    sba_dem_districts[!duplicated(sba_dem_districts)]
  sba_dem_districts <- sort(sba_dem_districts)

  #Process all districts
  for (i in 1:length(sba_dem_districts)) {
    district = sba_dem_districts[i]
    sba_dem_subset <- sba_dem[sba_dem$District == district,]
    
    chartScatter(
      aX = sba_dem$PercentFreeorReducedPricedMeals, aY = sba_dem$MathPercentMetStandardIncludingPrevPass,
      aTitle = paste(
        "WA Public Schools with 8th Graders with 200+ Students \n 2015 SBA Results (",
        district," Schools Highlighted)",sep = ""
      ),
      aXLabel = "% low income students \n \n Source: OSPI", aYLabel = "% of 8th Graders Who Met Standard in Math",
      aSubsetX = sba_dem_subset$PercentFreeorReducedPricedMeals,
      aSubsetY = sba_dem_subset$MathPercentMetStandardIncludingPrevPass, aShowSubset = T, aColor = "lightgray",
      aShowLegend = T, aLegend = sba_dem_subset$School, aShowFittedLine = T,
      aSavePlotFilename = paste(
        "ReportsAutoGenerated//SBA Math 8th Grade",district,"Schools 2015.png"
      ),aSavePlot = T
    )
  }
}
